//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace plugin_trinity.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class trinityString {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal trinityString() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("plugin_trinity.Properties.trinityString", typeof(trinityString).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Closed 的本地化字符串。
        /// </summary>
        internal static string channelClosed {
            get {
                return ResourceManager.GetString("channelClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Channel Transaction 的本地化字符串。
        /// </summary>
        internal static string ChannelMenuTitle {
            get {
                return ResourceManager.GetString("ChannelMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Opened 的本地化字符串。
        /// </summary>
        internal static string channelOpened {
            get {
                return ResourceManager.GetString("channelOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid payment code 的本地化字符串。
        /// </summary>
        internal static string CheckPaymentCode {
            get {
                return ResourceManager.GetString("CheckPaymentCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please choice a valid account for channel operation 的本地化字符串。
        /// </summary>
        internal static string choiceChannelAddress {
            get {
                return ResourceManager.GetString("choiceChannelAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please choice a channel from channel list 的本地化字符串。
        /// </summary>
        internal static string choiceDeleteChannel {
            get {
                return ResourceManager.GetString("choiceDeleteChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please choice a valid channel from channel list 的本地化字符串。
        /// </summary>
        internal static string choiceTransferChannel {
            get {
                return ResourceManager.GetString("choiceTransferChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please choice valid asset type 的本地化字符串。
        /// </summary>
        internal static string invalidAssetType {
            get {
                return ResourceManager.GetString("invalidAssetType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please input correct query range 的本地化字符串。
        /// </summary>
        internal static string invalidChannelQueryRange {
            get {
                return ResourceManager.GetString("invalidChannelQueryRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please input valid query value 的本地化字符串。
        /// </summary>
        internal static string invalidChannelQueryValue {
            get {
                return ResourceManager.GetString("invalidChannelQueryValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please choice valid query condition 的本地化字符串。
        /// </summary>
        internal static string invalidQueryCondition {
            get {
                return ResourceManager.GetString("invalidQueryCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter full transfer information 的本地化字符串。
        /// </summary>
        internal static string invalidTransferParameters {
            get {
                return ResourceManager.GetString("invalidTransferParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Monitoring Block Height 的本地化字符串。
        /// </summary>
        internal static string monitorBlock {
            get {
                return ResourceManager.GetString("monitorBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transfer to 的本地化字符串。
        /// </summary>
        internal static string TransferMessage {
            get {
                return ResourceManager.GetString("TransferMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transfer Transaction Confirmation 的本地化字符串。
        /// </summary>
        internal static string TransferPromptTitle {
            get {
                return ResourceManager.GetString("TransferPromptTitle", resourceCulture);
            }
        }
    }
}
